/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminMembersRouteImport } from './routes/_admin/members'
import { Route as AdminSocietiesRouteImport } from './routes/_admin/societies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSocietiesRoute = AdminSocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/members': typeof AdminMembersRoute
  '/societies': typeof AdminSocietiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/members': typeof AdminMembersRoute
  '/societies': typeof AdminSocietiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/members': typeof AdminMembersRoute
  '/_admin/societies': typeof AdminSocietiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/members' | '/societies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/members' | '/societies'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/dashboard'
    | '/_admin/members'
    | '/_admin/societies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/members': {
      id: '/_admin/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/societies': {
      id: '/_admin/societies'
      path: '/societies'
      fullPath: '/societies'
      preLoaderRoute: typeof AdminSocietiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSocietiesRoute: typeof AdminSocietiesRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminSocietiesRoute: AdminSocietiesRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
